products = [
    {
        '_id': '1',
        'name': 'Black Skretchable Jeans',
        'image': '/images/j1.jpg',
        'description':
        'They are perfect for those who prioritize both fashion and comfort.',
        'brand': 'Flying Edition',
        'category': 'Jeans',
        'price': 1299,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Dark Blue Jeans',
        'image': '/images/j2.jpg',
        'description':
        'They are perfect for those who prioritize both fashion and comfort.',
        'brand': 'White Devil',
        'category': 'Jeans',
        'price': 1099,
        'countInStock': 7,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'Blue Jeans',
        'image': '/images/j6.jpg',
        'description':
        'They are perfect for those who prioritize both fashion and comfort.',
        'brand': 'Superdry',
        'category': 'Jeans',
        'price': 999,
        'countInStock': 5,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Blue Laser Jeans',
        'image': '/images/j4.jpg',
        'description':
        'They are perfect for those who prioritize both fashion and comfort.',
        'brand': 'White Devil',
        'category': 'Jeans',
        'price': 1249,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '5',
        'name': 'Blue Funky Jeans',
        'image': '/images/j5.jpg',
        'description':
        'They are perfect for those who prioritize both fashion and comfort.',
        'brand': 'Mad Bull',
        'category': 'Jeans',
        'price': 1099,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': '6',
        'name': 'Black Funky Jeans',
        'image': '/images/j3.jpg',
        'description':
        'They are perfect for those who prioritize both fashion and comfort.',
        'brand': 'White Devil',
        'category': 'Jeans',
        'price': 1299,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
]
